### ISSUE TITLE
Question about PTMs in input sequence

### ISSUE THREAD

**Issue by JannikSchneider12** [gagneurlab/spectralis#2]
Hello everyone,

I want to use the model to rescore my peptide identifications. However the sequences contain also some PTMs in the form of the mass inside the string, e.g. "M+15.995VSDLAGEGVC+57.021K". Should I remove every modification for a correct rescoring or can I just pass them?

Thanks for your time and help

**Comment by andradesalazar** [comment]
Hi @JannikSchneider12,

thanks for reaching out.
Spectralis is currently able to score peptides containing methionine oxidation (Mox) and carbamidomethyl (C) was specified as a fixed modification. That means your example sequence should be rescored without problems. For this, you would need to parse the residues M+15.995 and C+57.021 to the ProForma syntax, i.e.  "M[UNIMOD:35]" and "C[UNIMOD:4]":
"M[UNIMOD:35]VSDLAGEGVC[UNIMOD:4]".
That should hopefully work.

Best,
Daniela
